services:
  shadowsocks-server:
    build:
      context: .
    image: shadowsocks-rust:latest
    ports:
      - "8388:8388"
      - "8388:8388/udp"
    volumes:
      - ./config:/opt/shadowsocks-rust/config
    restart: always
    container_name: shadowsocks-rust-server